# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

target 'BraintreeRN' do

  # Pods for BraintreeRN
  pod 'BraintreeDropIn'

  # Includes Cards and PayPal
  pod 'Braintree'
  pod 'Braintree/PaymentFlow'

  # Optionally include additional Pods
  pod 'Braintree/DataCollector'
  pod 'Braintree/PayPal'
  pod 'Braintree/Apple-Pay'
  
  pod 'Alamofire', '~> 4.8'

  pod 'SwiftyJSON', '~> 4.0'

  # uncomment the next line to support credit card scanning
  pod 'CardIO'

end
